### ISSUE TITLE
Bootstrap's Javascript requires jQuery

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/shell#2]
**Original issue as written by @adriatic :**

The code in this repository is the unmodified **[skeleton-esnext](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext)** taken from **[today's release](https://github.com/aurelia/skeleton-navigation/releases/tag/1.0.0-beta.1.3.1)** (not from the master branch).

The **[README](https://github.com/monterey-framework/skeleton-prototype/blob/master/README.md)** is modified version of the original, with focus to the electron environment only.

The error below was encountered running the following commands:
```
npm install
jspm install
gulp build
electron index.js
```

![image](https://cloud.githubusercontent.com/assets/2712405/16291000/29c57fdc-38d0-11e6-8c29-99b57f71979f.png)

**Note**: I reported this to aurelia : https://github.com/aurelia/skeleton-navigation/issues/532

**Comment by JeroenVinke** [comment]
Worked around by adding `<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>` in index.html. This is an issue that has to be solved in JSPM and there is a PR [here](https://github.com/jspm/registry/pull/914#issuecomment-226754661). So we'll stick with the workaround until it is fixed

**Comment by adriatic** [comment]
Well done

**Comment by EisenbergEffect** [comment]
Thanks for this @JeroenVinke :) This slipped right under the radar.
