### ISSUE TITLE
Project scaffolding feature

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/shell#5]
Now that we have a basic application running ([as shown here](https://github.com/monterey-framework/shell/issues/4#issue-162292670)), we can design, plan and implement the project scaffolding feature.

I believe we would need to make a GUI based on [this JSON file](https://github.com/aurelia/cli/blob/master/lib/commands/new/new-application.json) and then somehow feed the user input to aurelia-cli.

**Comment by JeroenVinke** [comment]
https://gist.github.com/vegarringdal/161999c86be0383f0b06ae48daa2558e (Made by Vegar)

**Comment by JeroenVinke** [comment]
https://gist.github.com/vegarringdal/161999c86be0383f0b06ae48daa2558e helped me a lot :smile:

**Comment by vegarringdal** [comment]
I just tried the shell :-)
See you use it

**Comment by vegarringdal** [comment]
Source where I got the code from the aurelia-cli
https://github.com/aurelia/cli/blob/master/lib/workflow/activities/project-create.js

Nice to know of in case they made modifications that break ours

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16493085/8da1878e-3ee4-11e6-88da-b75994b99a85.png)
