### ISSUE TITLE
NPM install new project in the background

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/shell#7]
Creating new aurelia projects doesn't take long, but `npm install` on newly created projects is slow

![image](https://cloud.githubusercontent.com/assets/2189477/16362738/c8b6354e-3bb6-11e6-925b-5be80201d5c7.png)

you don't want to be waiting at this screen for 10+ minutes. 

So I propose that we scaffold the project, but install the NPM modules in the background (when we get to the [main screen](http://i.imgur.com/yihXvfF.png).

**Comment by adriatic** [comment]
I agree that waiting for the background processes for **that long** will kill the whole idea. We could completely detach the main thread (where we get to see the UI) from the background process (aka rendering processes, where node.js runs our npm utilities)

Even if we could run renderer processes asynchronously (something I do not advertise) it would not do any good as the main process still could not finish until the renderer process (assuming that we have just one) does.

The only solution is to accept that running npm / jspm / webpack takes what it takes and then make the main thread entertain the user with something different from the spinning circle - which will spin for the whole duration of

![image](https://cloud.githubusercontent.com/assets/2712405/16362830/f878d99c-3b86-11e6-8492-5ba74ec1594b.png)

**Comment by JeroenVinke** [comment]
@adriatic I want to give this a shot anyway. I believe the actual npm install was done in the background, so we can keep using the UI. I propose that we scaffold the project immediately and switch to monterey's main screen. Then we can show that NPM modules are still being installed, but you could continue to use monterey in the mean time.

![image](https://cloud.githubusercontent.com/assets/2189477/16390904/190a5806-3ca5-11e6-9969-84eb701d1acf.png)

**Comment by adriatic** [comment]
Yes, I see this the same way as you do and my [comment](https://github.com/monterey-framework/shell/issues/7#issuecomment-228603463) was not suggesting anything different :-)
